"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from PortableBinary import version

APP = ['PortableBinaryGUI.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options=dict(
        py2app=dict(
        plist=dict(
            CFBundleIdentifier="com.jazzzny.PortableBinaryGUI",
            CFBundleVersion=version,
            CFBundleShortVersionString=version,
        ))),
    setup_requires=['py2app'],
)
