name: Build Portable Binary GUI and CLI

on:
    push:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Python.org Python
              run: |
                wget https://www.python.org/ftp/python/3.12.5/python-3.12.5-macos11.pkg
                sudo installer -pkg python-3.12.5-macos11.pkg -target /

            - name: Install dependencies
              run: |
                    /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 -m pip install --upgrade pip
                    /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 -m pip install pyinstaller


            - name: Build GUI
              run: |
                    pyinstaller PortableBinaryGUI.py --onefile --target-architecture universal2 --strip --name PortableBinary-GUI

            - name: Build CLI
              run: |
                    pyinstaller PortableBinary.py --onefile --target-architecture universal2 --strip --name PortableBinary

            - name: Upload CLI
              uses: actions/upload-artifact@v4
              with:
                    name: PortableBinary
                    path: dist/PortableBinary

            - name: Upload GUI
              uses: actions/upload-artifact@v4
              with:
                    name: PortableBinary-GUI
                    path: dist/PortableBinary-GUI

            - name: Get short commit hash
              id: commit_hash
              run: echo "::set-output name=hash::$(echo $GITHUB_SHA | cut -c1-7)"

            - name: Create rolling release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  dist/PortableBinary
                  dist/PortableBinary-GUI
                # tag name should be commit id
                tag_name: ${{ steps.commit_hash.outputs.hash }}
                name: Portable Binary ${{ steps.commit_hash.outputs.hash }}
                body: |
                  This is a prebuilt release for the latest commit.
                  It contains the Portable Binary CLI and GUI.
                make_latest: true


